/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    transactions: Transaction;
    'transaction-categories': TransactionCategory;
    'cost-centers': CostCenter;
    aircraft: Aircraft;
    flights: Flight;
    'flight-logs': FlightLog;
    'import-runs': ImportRun;
    'fuel-entries': FuelEntry;
    'general-costs': GeneralCost;
    'access-tokens': AccessToken;
    members: Member;
    'membership-fee-types': MembershipFeeType;
    'membership-fee-stats': MembershipFeeStat;
    'working-hours': WorkingHour;
    forms: Form;
    'form-submissions': FormSubmission;
    'payload-kv': PayloadKv;
    'payload-folders': FolderInterface;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    'payload-folders': {
      documentsAndFolders: 'payload-folders' | 'media';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    transactions: TransactionsSelect<false> | TransactionsSelect<true>;
    'transaction-categories': TransactionCategoriesSelect<false> | TransactionCategoriesSelect<true>;
    'cost-centers': CostCentersSelect<false> | CostCentersSelect<true>;
    aircraft: AircraftSelect<false> | AircraftSelect<true>;
    flights: FlightsSelect<false> | FlightsSelect<true>;
    'flight-logs': FlightLogsSelect<false> | FlightLogsSelect<true>;
    'import-runs': ImportRunsSelect<false> | ImportRunsSelect<true>;
    'fuel-entries': FuelEntriesSelect<false> | FuelEntriesSelect<true>;
    'general-costs': GeneralCostsSelect<false> | GeneralCostsSelect<true>;
    'access-tokens': AccessTokensSelect<false> | AccessTokensSelect<true>;
    members: MembersSelect<false> | MembersSelect<true>;
    'membership-fee-types': MembershipFeeTypesSelect<false> | MembershipFeeTypesSelect<true>;
    'membership-fee-stats': MembershipFeeStatsSelect<false> | MembershipFeeStatsSelect<true>;
    'working-hours': WorkingHoursSelect<false> | WorkingHoursSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-folders': PayloadFoldersSelect<false> | PayloadFoldersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name?: string | null;
  /**
   * Aktivieren Sie die Funktionen, auf die dieser Benutzer zugreifen kann
   */
  permissions?: {
    /**
     * Zugriff auf Kontobewegungen (Import, Übersicht, Jahresvergleich)
     */
    transactions?: boolean | null;
    /**
     * Zugriff auf Flugzeugverwaltung und Übersicht
     */
    aircraft?: boolean | null;
    /**
     * Zugriff auf Flugstunden & Starts
     */
    flightLogs?: boolean | null;
    /**
     * Zugriff auf Kostenstellen-Verwaltung
     */
    costCenters?: boolean | null;
    /**
     * Zugriff auf Zuordnung von Kosten zu Flugzeugen
     */
    costAllocations?: boolean | null;
    /**
     * Zugriff auf Jahresvergleich der Kontobewegungen
     */
    yearlyComparison?: boolean | null;
    /**
     * Zugriff auf Kostenermittlung pro Flugzeug
     */
    costCalculation?: boolean | null;
    /**
     * Zugriff auf Kraftstofferfassung
     */
    fuelTracking?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt?: string | null;
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  folder?: (string | null) | FolderInterface;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    square?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    small?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    xlarge?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders".
 */
export interface FolderInterface {
  id: string;
  name: string;
  folder?: (string | null) | FolderInterface;
  documentsAndFolders?: {
    docs?: (
      | {
          relationTo?: 'payload-folders';
          value: string | FolderInterface;
        }
      | {
          relationTo?: 'media';
          value: string | Media;
        }
    )[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  folderType?: 'media'[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transactions".
 */
export interface Transaction {
  id: string;
  date: string;
  description: string;
  /**
   * Betrag in Euro (negativ für Ausgaben, positiv für Einnahmen)
   */
  amount: number;
  /**
   * Wird automatisch basierend auf dem Betrag gesetzt, kann aber manuell geändert werden
   */
  type: 'income' | 'expense';
  /**
   * Optional: Kategorie für diese Bewegung
   */
  category?: (string | null) | TransactionCategory;
  /**
   * Optional: Kostenstelle für diese Bewegung (z.B. Verwaltung, Flugbetrieb)
   */
  costCenter?: (string | null) | CostCenter;
  /**
   * Zusätzliche Referenznummer oder Verwendungszweck
   */
  reference?: string | null;
  /**
   * Markieren Sie diese Bewegung als verarbeitet/kategorisiert
   */
  processed?: boolean | null;
  /**
   * Zusätzliche Notizen zu dieser Bewegung
   */
  notes?: string | null;
  /**
   * Ordnen Sie diese Kosten mehreren Stellen zu (Flugzeugen oder allgemeinen Kosten) mit Gewichtung
   */
  costAllocations?:
    | {
        /**
         * Wählen Sie, ob Sie einem Flugzeug oder allgemeinen Kosten zuordnen möchten
         */
        allocationType: 'aircraft' | 'generalCost';
        /**
         * Flugzeug, dem diese Kosten zugeordnet werden
         */
        aircraft?: (string | null) | Aircraft;
        /**
         * Allgemeine Kostenstelle, der diese Kosten zugeordnet werden
         */
        generalCost?: (string | null) | GeneralCost;
        /**
         * Prozentualer Anteil dieser Kostenstelle (z.B. 50 für 50%)
         */
        weight: number;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transaction-categories".
 */
export interface TransactionCategory {
  id: string;
  name: string;
  type: 'income' | 'expense';
  /**
   * Hex-Farbcode für die Anzeige (z.B. #3B82F6)
   */
  color?: string | null;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cost-centers".
 */
export interface CostCenter {
  id: string;
  /**
   * Bezeichnung der Kostenstelle (z.B. "Verwaltung", "Flugbetrieb", "Marketing")
   */
  name: string;
  /**
   * Optional: Kurzcode für die Kostenstelle (z.B. "VW", "FB", "MK")
   */
  code?: string | null;
  /**
   * Zusätzliche Informationen zur Kostenstelle
   */
  description?: string | null;
  /**
   * Ist diese Kostenstelle aktiv und kann zugeordnet werden?
   */
  active?: boolean | null;
  /**
   * Optional: Hex-Code für die Anzeige der Kostenstelle (z.B. #FF0000)
   */
  color?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "aircraft".
 */
export interface Aircraft {
  id: string;
  /**
   * Offizielles Kennzeichen des Flugzeugs (z.B. D-ABCD)
   */
  registration: string;
  /**
   * Optional: Zusätzliche Bezeichnung oder Name
   */
  name?: string | null;
  /**
   * Hauptkategorie des Flugzeugs
   */
  aircraftGroup: 'ul' | 'glider' | 'motor' | 'motor-glider' | 'helicopter' | 'other';
  /**
   * Hersteller des Flugzeugs (z.B. Cessna, Piper, etc.)
   */
  manufacturer?: string | null;
  /**
   * Modellbezeichnung (z.B. C172, PA-28, etc.)
   */
  model?: string | null;
  /**
   * Datum des Erwerbs
   */
  purchaseDate?: string | null;
  /**
   * Anschaffungspreis des Flugzeugs
   */
  purchasePrice?: number | null;
  /**
   * Jährliche Versicherungskosten
   */
  insurance?: number | null;
  /**
   * Jährliche Kosten für Hangar oder Standplatz
   */
  hangar?: number | null;
  /**
   * Durchschnittliche Kosten für jährliche Inspektion
   */
  annualInspection?: number | null;
  /**
   * Sonstige jährliche Fixkosten
   */
  fixedCosts?: number | null;
  /**
   * Aktuelle Gesamtmotorstunden
   */
  engineHours?: number | null;
  /**
   * Aktuelle Gesamtflugstunden
   */
  totalFlightHours?: number | null;
  /**
   * Durchschnittlicher Kraftstoffverbrauch pro Stunde
   */
  fuelConsumption?: number | null;
  /**
   * Aktueller Kraftstoffpreis pro Liter
   */
  fuelPrice?: number | null;
  /**
   * Durchschnittliche Wartungskosten pro Flugstunde
   */
  maintenanceCostPerHour?: number | null;
  /**
   * Zusätzliche Informationen zum Flugzeug
   */
  notes?: string | null;
  /**
   * Flugzeug ist aktiv im Betrieb
   */
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "general-costs".
 */
export interface GeneralCost {
  id: string;
  /**
   * Optional: ordnet diese Kostenstelle einer Obergruppe zu (z.B. Fixkosten → Pacht)
   */
  parent?: (string | null) | GeneralCost;
  /**
   * Bezeichnung der allgemeinen Kosten (z.B. "Pacht", "Versicherung", "Wartung")
   */
  name: string;
  /**
   * Zusätzliche Informationen zu diesen Kosten
   */
  description?: string | null;
  /**
   * Kann diese allgemeine Kostenstelle für Einnahmen zugeordnet werden?
   */
  availableForIncome?: boolean | null;
  /**
   * Kann diese allgemeine Kostenstelle für Ausgaben zugeordnet werden?
   */
  availableForExpense?: boolean | null;
  /**
   * Ist diese allgemeine Kostenstelle aktiv und kann zugeordnet werden?
   */
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "flights".
 */
export interface Flight {
  id: string;
  /**
   * Datum des Flugs
   */
  date: string;
  /**
   * Leer bei Import wenn Vereins-LFZ ≠ Ja (kein Vereinsflugzeug)
   */
  aircraft?: (string | null) | Aircraft;
  /**
   * Hauptpilot des Flugs
   */
  pilot?: (string | null) | Member;
  /**
   * Name des Piloten (falls nicht als Mitglied zugeordnet)
   */
  pilotName?: string | null;
  /**
   * Begleiter/Begleitpilot
   */
  copilot?: (string | null) | Member;
  /**
   * Name des Begleiters (falls nicht als Mitglied zugeordnet)
   */
  copilotName?: string | null;
  /**
   * Startzeit im Format HH:MM
   */
  startTime?: string | null;
  /**
   * Landezeit im Format HH:MM
   */
  landingTime?: string | null;
  /**
   * Flugdauer in Stunden
   */
  flightHours: number;
  /**
   * Flugdauer in Minuten (wird automatisch in Stunden umgerechnet)
   */
  flightMinutes?: number | null;
  /**
   * Anzahl der Starts (meist 1)
   */
  starts: number;
  /**
   * Abflugort
   */
  departureLocation?: string | null;
  /**
   * Landeort
   */
  landingLocation?: string | null;
  /**
   * Anzahl und Art der Landungen
   */
  landings?: string | null;
  flightType?: ('P' | 'S' | 'N') | null;
  /**
   * Zusätzliche Informationen zum Flug
   */
  notes?: string | null;
  /**
   * Referenz auf den Import-Lauf (für Rückgängig-machen)
   */
  importRun?: (string | null) | ImportRun;
  /**
   * Dateiname beim Import
   */
  sourceFileName?: string | null;
  /**
   * Jahr aus Import-Datum
   */
  sourceYear?: number | null;
  /**
   * Optional für Dedupe/Debug
   */
  sourceImportId?: string | null;
  /**
   * Hash zur Duplikaterkennung
   */
  sourceRowHash?: string | null;
  /**
   * Inhalt aus Spalte Lfz. (Hauptflugbuch)
   */
  sourceAircraftRegistration?: string | null;
  /**
   * Inhalt aus Spalte Schlepp-LFZ
   */
  sourceTowAircraftRegistration?: string | null;
  /**
   * Aus Spalte Schleppzeit
   */
  sourceTowMinutes?: number | null;
  /**
   * Aus Spalte Zeit
   */
  sourceMinutes?: number | null;
  /**
   * Berechnete Segelflug-Arbeitsminuten
   */
  workingMinutesGlider?: number | null;
  /**
   * Berechnete Motorflug-Arbeitsminuten
   */
  workingMinutesMotor?: number | null;
  /**
   * Berechnete Schlepp-Arbeitsminuten
   */
  workingMinutesTow?: number | null;
  /**
   * Status der Pilot-Zuordnung
   */
  memberMatchStatus?: ('matched' | 'unmatched' | 'ambiguous') | null;
  /**
   * Top-Kandidaten bei ambiguous/unmatched
   */
  memberMatchCandidates?:
    | {
        name?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "members".
 */
export interface Member {
  id: string;
  /**
   * Vollständiger Name des Mitglieds
   */
  name: string;
  /**
   * Eindeutige Mitgliedsnummer
   */
  memberNumber?: string | null;
  /**
   * E-Mail-Adresse des Mitglieds
   */
  email?: string | null;
  /**
   * Telefonnummer
   */
  phone?: string | null;
  /**
   * Vollständige Adresse
   */
  address?: string | null;
  /**
   * Ist das Mitglied aktiv?
   */
  active?: boolean | null;
  /**
   * Zusätzliche Informationen
   */
  notes?: string | null;
  /**
   * SHA1 der importierten Felder für Delta-Import
   */
  importFingerprint?: string | null;
  lastImportedAt?: string | null;
  /**
   * Herkunft des letzten Imports
   */
  sourceSystem?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "import-runs".
 */
export interface ImportRun {
  id: string;
  type: 'flights';
  fileName: string;
  fileSize?: number | null;
  /**
   * SHA1 über Datei-Inhalt zur Identifikation
   */
  fileHash?: string | null;
  importedAt: string;
  importedBy?: (string | null) | User;
  /**
   * Abgeleitetes Jahr aus den importierten Daten
   */
  year?: number | null;
  stats?: {
    created?: number | null;
    updated?: number | null;
    skipped?: number | null;
    errors?: number | null;
    unmatchedMembers?: number | null;
  };
  notes?: string | null;
  /**
   * Import wurde rückgängig gemacht (zugehörige Flüge gelöscht)
   */
  isDeleted?: boolean | null;
  deletedAt?: string | null;
  deletedBy?: (string | null) | User;
  deletedFlightsCount?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "flight-logs".
 */
export interface FlightLog {
  id: string;
  aircraft: string | Aircraft;
  /**
   * Jahr für das diese Daten gelten
   */
  year: number;
  /**
   * Anzahl der Starts in diesem Jahr
   */
  starts: number;
  /**
   * Gesamte Flugstunden in diesem Jahr
   */
  flightHours: number;
  /**
   * Zusätzliche Informationen zu diesem Jahr
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fuel-entries".
 */
export interface FuelEntry {
  id: string;
  date: string;
  /**
   * Flugzeug, für das der Kraftstoff getankt wurde
   */
  aircraft: string | Aircraft;
  /**
   * Art des Kraftstoffs
   */
  fuelType: 'avgas' | 'mogas';
  /**
   * Name der Person, die getankt hat
   */
  name: string;
  /**
   * Zählerstand vor dem Tanken
   */
  meterReadingOld: number;
  /**
   * Zählerstand nach dem Tanken
   */
  meterReadingNew: number;
  /**
   * Getankte Liter (wird automatisch berechnet: Zählerstand neu - Zählerstand alt)
   */
  liters: number;
  /**
   * Preis pro Liter in Euro
   */
  pricePerLiter: number;
  /**
   * Gesamtpreis (wird automatisch berechnet)
   */
  totalPrice: number;
  /**
   * Name der Tankstelle
   */
  gasStation?: string | null;
  /**
   * Rechnungsnummer der Tankstelle
   */
  invoiceNumber?: string | null;
  /**
   * Hochgeladene Rechnung
   */
  invoice?: (string | null) | Media;
  /**
   * Zusätzliche Notizen
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "access-tokens".
 */
export interface AccessToken {
  id: string;
  /**
   * Bezeichnung für diesen Zugang (z.B. "Kraftstofferfassung - Hangar 1")
   */
  name: string;
  /**
   * Eindeutiger Zugangstoken (wird automatisch generiert)
   */
  token: string;
  /**
   * Welche Bereiche sind mit diesem Token zugänglich?
   */
  permissions?: 'fuelTracking'[] | null;
  /**
   * Optional: Ab wann ist dieser Zugang nicht mehr gültig?
   */
  expiresAt?: string | null;
  /**
   * Ist dieser Zugang aktiv und kann verwendet werden?
   */
  active?: boolean | null;
  /**
   * Wann wurde dieser Zugang zuletzt verwendet?
   */
  lastUsedAt?: string | null;
  /**
   * Wie oft wurde dieser Zugang verwendet?
   */
  usageCount?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "membership-fee-types".
 */
export interface MembershipFeeType {
  id: string;
  /**
   * z.B. „Aktives Mitglied“, „Passives Mitglied“, „Fördermitglied“
   */
  name: string;
  /**
   * Optionale technische Kennung (z.B. AKTIV, PASSIV)
   */
  code?: string | null;
  /**
   * Vorgabewert, der bei neuen Ständen vorbelegt werden kann
   */
  defaultAmount?: number | null;
  active?: boolean | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "membership-fee-stats".
 */
export interface MembershipFeeStat {
  id: string;
  /**
   * Wird automatisch aus Jahr und Beitragsart berechnet.
   */
  adminLabel?: string | null;
  /**
   * Geschäftsjahr, für das der Stand gilt (z.B. 2024).
   */
  year: number;
  /**
   * Datum, zu dem der Mitgliederbestand bewertet wurde.
   */
  snapshotDate: string;
  feeType: string | MembershipFeeType;
  /**
   * z.B. 10 aktive Mitglieder.
   */
  memberCount: number;
  /**
   * z.B. 700 € pro aktivem Mitglied.
   */
  amountPerMember: number;
  /**
   * Wird automatisch als Anzahl * Beitrag berechnet, kann bei Bedarf aber manuell angepasst werden.
   */
  totalIncome?: number | null;
  /**
   * Optional: Kostengruppe, der diese Beitragseinnahmen gutgeschrieben werden (z.B. „Fixkosten“). Ist nichts gesetzt, wird die Zuordnung der Beitragsart verwendet.
   */
  generalCost?: (string | null) | GeneralCost;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "working-hours".
 */
export interface WorkingHour {
  id: string;
  /**
   * Wird automatisch generiert.
   */
  adminLabel?: string | null;
  /**
   * Mitglied, das die Arbeitsstunden geleistet hat
   */
  member: string | Member;
  /**
   * Datum, an dem die Arbeitsstunden geleistet wurden
   */
  date: string;
  /**
   * Anzahl der geleisteten Arbeitsstunden
   */
  hours: number;
  /**
   * Art der geleisteten Arbeitsstunden
   */
  type: 'glider' | 'motor' | 'administration' | 'maintenance' | 'other';
  /**
   * Zusätzliche Informationen zu den geleisteten Arbeitsstunden
   */
  description?: string | null;
  /**
   * Interne Notizen
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: string;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'country';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'state';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  /**
   * Choose whether to display an on-page message or redirect to a different page after they submit the form.
   */
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  /**
   * Send custom emails when the form submits. Use comma separated lists to send the same email to multiple recipients. To reference a value from this form, wrap that field's name with double curly brackets, i.e. {{firstName}}. You can use a wildcard {{*}} to output all data and {{*:table}} to format it as an HTML table in the email.
   */
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        /**
         * Enter the message that should be sent in this email.
         */
        message?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: string;
  form: string | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'transactions';
        value: string | Transaction;
      } | null)
    | ({
        relationTo: 'transaction-categories';
        value: string | TransactionCategory;
      } | null)
    | ({
        relationTo: 'cost-centers';
        value: string | CostCenter;
      } | null)
    | ({
        relationTo: 'aircraft';
        value: string | Aircraft;
      } | null)
    | ({
        relationTo: 'flights';
        value: string | Flight;
      } | null)
    | ({
        relationTo: 'flight-logs';
        value: string | FlightLog;
      } | null)
    | ({
        relationTo: 'import-runs';
        value: string | ImportRun;
      } | null)
    | ({
        relationTo: 'fuel-entries';
        value: string | FuelEntry;
      } | null)
    | ({
        relationTo: 'general-costs';
        value: string | GeneralCost;
      } | null)
    | ({
        relationTo: 'access-tokens';
        value: string | AccessToken;
      } | null)
    | ({
        relationTo: 'members';
        value: string | Member;
      } | null)
    | ({
        relationTo: 'membership-fee-types';
        value: string | MembershipFeeType;
      } | null)
    | ({
        relationTo: 'membership-fee-stats';
        value: string | MembershipFeeStat;
      } | null)
    | ({
        relationTo: 'working-hours';
        value: string | WorkingHour;
      } | null)
    | ({
        relationTo: 'forms';
        value: string | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: string | FormSubmission;
      } | null)
    | ({
        relationTo: 'payload-folders';
        value: string | FolderInterface;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  permissions?:
    | T
    | {
        transactions?: T;
        aircraft?: T;
        flightLogs?: T;
        costCenters?: T;
        costAllocations?: T;
        yearlyComparison?: T;
        costCalculation?: T;
        fuelTracking?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  folder?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        square?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        small?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        xlarge?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transactions_select".
 */
export interface TransactionsSelect<T extends boolean = true> {
  date?: T;
  description?: T;
  amount?: T;
  type?: T;
  category?: T;
  costCenter?: T;
  reference?: T;
  processed?: T;
  notes?: T;
  costAllocations?:
    | T
    | {
        allocationType?: T;
        aircraft?: T;
        generalCost?: T;
        weight?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transaction-categories_select".
 */
export interface TransactionCategoriesSelect<T extends boolean = true> {
  name?: T;
  type?: T;
  color?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cost-centers_select".
 */
export interface CostCentersSelect<T extends boolean = true> {
  name?: T;
  code?: T;
  description?: T;
  active?: T;
  color?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "aircraft_select".
 */
export interface AircraftSelect<T extends boolean = true> {
  registration?: T;
  name?: T;
  aircraftGroup?: T;
  manufacturer?: T;
  model?: T;
  purchaseDate?: T;
  purchasePrice?: T;
  insurance?: T;
  hangar?: T;
  annualInspection?: T;
  fixedCosts?: T;
  engineHours?: T;
  totalFlightHours?: T;
  fuelConsumption?: T;
  fuelPrice?: T;
  maintenanceCostPerHour?: T;
  notes?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "flights_select".
 */
export interface FlightsSelect<T extends boolean = true> {
  date?: T;
  aircraft?: T;
  pilot?: T;
  pilotName?: T;
  copilot?: T;
  copilotName?: T;
  startTime?: T;
  landingTime?: T;
  flightHours?: T;
  flightMinutes?: T;
  starts?: T;
  departureLocation?: T;
  landingLocation?: T;
  landings?: T;
  flightType?: T;
  notes?: T;
  importRun?: T;
  sourceFileName?: T;
  sourceYear?: T;
  sourceImportId?: T;
  sourceRowHash?: T;
  sourceAircraftRegistration?: T;
  sourceTowAircraftRegistration?: T;
  sourceTowMinutes?: T;
  sourceMinutes?: T;
  workingMinutesGlider?: T;
  workingMinutesMotor?: T;
  workingMinutesTow?: T;
  memberMatchStatus?: T;
  memberMatchCandidates?:
    | T
    | {
        name?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "flight-logs_select".
 */
export interface FlightLogsSelect<T extends boolean = true> {
  aircraft?: T;
  year?: T;
  starts?: T;
  flightHours?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "import-runs_select".
 */
export interface ImportRunsSelect<T extends boolean = true> {
  type?: T;
  fileName?: T;
  fileSize?: T;
  fileHash?: T;
  importedAt?: T;
  importedBy?: T;
  year?: T;
  stats?:
    | T
    | {
        created?: T;
        updated?: T;
        skipped?: T;
        errors?: T;
        unmatchedMembers?: T;
      };
  notes?: T;
  isDeleted?: T;
  deletedAt?: T;
  deletedBy?: T;
  deletedFlightsCount?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fuel-entries_select".
 */
export interface FuelEntriesSelect<T extends boolean = true> {
  date?: T;
  aircraft?: T;
  fuelType?: T;
  name?: T;
  meterReadingOld?: T;
  meterReadingNew?: T;
  liters?: T;
  pricePerLiter?: T;
  totalPrice?: T;
  gasStation?: T;
  invoiceNumber?: T;
  invoice?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "general-costs_select".
 */
export interface GeneralCostsSelect<T extends boolean = true> {
  parent?: T;
  name?: T;
  description?: T;
  availableForIncome?: T;
  availableForExpense?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "access-tokens_select".
 */
export interface AccessTokensSelect<T extends boolean = true> {
  name?: T;
  token?: T;
  permissions?: T;
  expiresAt?: T;
  active?: T;
  lastUsedAt?: T;
  usageCount?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "members_select".
 */
export interface MembersSelect<T extends boolean = true> {
  name?: T;
  memberNumber?: T;
  email?: T;
  phone?: T;
  address?: T;
  active?: T;
  notes?: T;
  importFingerprint?: T;
  lastImportedAt?: T;
  sourceSystem?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "membership-fee-types_select".
 */
export interface MembershipFeeTypesSelect<T extends boolean = true> {
  name?: T;
  code?: T;
  defaultAmount?: T;
  active?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "membership-fee-stats_select".
 */
export interface MembershipFeeStatsSelect<T extends boolean = true> {
  adminLabel?: T;
  year?: T;
  snapshotDate?: T;
  feeType?: T;
  memberCount?: T;
  amountPerMember?: T;
  totalIncome?: T;
  generalCost?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "working-hours_select".
 */
export interface WorkingHoursSelect<T extends boolean = true> {
  adminLabel?: T;
  member?: T;
  date?: T;
  hours?: T;
  type?: T;
  description?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        country?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        state?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders_select".
 */
export interface PayloadFoldersSelect<T extends boolean = true> {
  name?: T;
  folder?: T;
  documentsAndFolders?: T;
  folderType?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}